---
config:
  layout: elk
  theme: neutral
---
graph TD
  01["Jan<br />CISOWSKI<br />i=1, ih=0<br />jL=2, jhL=0<br />jR=3, jhR=0<br />"]
  01 <--> 02["Jerzy<br />CISOWSKI<br />i=2, ih=1<br />jL=2, jhL=1<br />jR=5, jhR=0<br />"]
  01 <--> 03["Jadwiga<br />OCHOT<br />i=3, ih=1<br />jL=4, jhL=0<br />jR=3, jhR=1<br />"]
  02 <--> 04["Władysław<br />CISOWSKI<br />i=4, ih=2<br />jL=2, jhL=2<br />jR=9, jhR=0<br />"]
  02 <--> 05["Wiesława<br />TOKARSKA<br />i=5, ih=2<br />jL=6, jhL=0<br />jR=5, jhR=1<br />"]
  03 <--> 06["Roman<br />OCHOT<br />i=6, ih=2<br />jLL=4, jhLL=1<br />jR=7, jhR=0<br />"]
  03 <--> 07["Walburga<br />ALKERT<br />i=7, ih=2<br />jL=8, jhL=0<br />jR=3, jhR=2<br />"]
  04 <--> 08["Jan<br />CISSOWSKI<br />i=8, ih=3<br />jL=2, jhL=3<br />jR=17, jhR=0<br />"]
  04 <--> 09["Maria<br />NIEMIEC<br />i=9, ih=3<br />jL=10, jhL=0<br />jR=9, jhR=1<br />"]
  05 <--> 10["Bolesław<br />TOKARSKI<br />i=10, ih=3<br />jL=6, jhL=1<br />jR=15, jhR=0<br />"]
  05 <--> 11["Antonina<br />REPETOWICZ<br />i=11, ih=3<br />jL=12, jhL=0<br />jR=5, jhR=2<br />"]
  06 <--> 12["Bartłomiej<br />OCHOD<br />i=12, ih=3<br />jL=4, jhL=2<br />jR=13, jhR=0<br />"]
  06 <--> 13["Wiktoria<br />JOACHIMSKA<br />i=13, ih=3<br />jL=14, jhL=0<br />jR=7, jhR=1<br />"]
  07 <--> 14["Karol<br />ALKERT<br />i=14, ih=3<br />jL=8, jhL=1<br />jR=11, jhR=0<br />"]
  07 <--> 15["Julianna<br />PIETRAS<br />i=15, ih=3<br />jL=16, jhL=0<br />jR=3, jhR=3<br />"]

  style 01 fill:#dd74a0,stroke:#333,stroke-width:1px
  style 02 fill:#d18a23,stroke:#333,stroke-width:1px
  style 03 fill:#d18a23,stroke:#333,stroke-width:1px
  style 04 fill:#9ea329,stroke:#333,stroke-width:1px
  style 05 fill:#9ea329,stroke:#333,stroke-width:1px
  style 06 fill:#9ea329,stroke:#333,stroke-width:1px
  style 07 fill:#9ea329,stroke:#333,stroke-width:1px
  style 08 fill:#52b36c,stroke:#333,stroke-width:1px
  style 09 fill:#52b36c,stroke:#333,stroke-width:1px
  style 10 fill:#52b36c,stroke:#333,stroke-width:1px
  style 11 fill:#52b36c,stroke:#333,stroke-width:1px
  style 12 fill:#52b36c,stroke:#333,stroke-width:1px
  style 13 fill:#52b36c,stroke:#333,stroke-width:1px
  style 14 fill:#52b36c,stroke:#333,stroke-width:1px
  style 15 fill:#52b36c,stroke:#333,stroke-width:1px
